[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
auto_detect_remappings = false
optimizer_runs = 800
via_ir = false



# See more config options https://github.com/foundry-rs/foundry/tree/master/config